'use client';
import { useEffect, useState } from 'react';
import type { StyleProfile } from '../lib/style-model';
import type { Draft } from '../lib/model';
import type { AiConnection, AiJob } from '../lib/ai-model';

type Props = { profiles: StyleProfile[]; draft: Draft; dirty: boolean; online: boolean; connection: AiConnection; jobs: AiJob[]; request: (action: string, values?: object) => Promise<any>; refresh: () => Promise<void>; applied: (draft: Draft) => void; lock: (busy: boolean) => void };
export function AiPanel({ profiles, draft, dirty, online, connection, jobs, request, refresh, applied, lock }: Props) {
  const [profileId,setProfileId]=useState(''); const [left,setLeft]=useState(''); const [right,setRight]=useState('');
  const [model, setModel] = useState(''); const [selection, setSelection] = useState(''); const [instruction, setInstruction] = useState(''); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false); const [versions, setVersions] = useState<Draft[]>([]);
  useEffect(() => { if (!connection.models.some(m => m.id === model)) setModel((connection.models.find(m => m.isDefault) || connection.models[0])?.id || ''); }, [connection.models, model]);
  useEffect(()=>{if(profileId&&!profiles.some(p=>p.id===profileId&&(p.kind==='common'||p.kind===draft.kind)))setProfileId('');},[profiles,profileId,draft.kind]);
  useEffect(() => { setSelection(''); setInstruction(''); setVersions([]); }, [draft.id]);
  async function run(action: string, values: object = {}) { setBusy(true); lock(true); setMessage(''); try { const value = await request(action, values); await refresh(); return value; } catch (error) { setMessage(error instanceof Error ? error.message : '요청 실패'); } finally { setBusy(false); lock(false); } }
  const own = jobs.filter(j => j.draft.id === draft.id);
  const active = own.some(j => ['queued','running'].includes(j.state));
  return <section className="panel ai-panel"><div className="section-heading"><h2>ChatGPT로 글 초안 만들기</h2><span className="tag">프로젝트 · 기술 · PS</span></div>
    <p>저장한 요약·문제·참고 자료와 사진으로 개요·본문·사진 설명을 만듭니다. 결과를 검토한 뒤 원고에 적용하세요.</p>
    <div className="button-row"><button disabled={busy || !online || connection.state === 'connecting' || active} onClick={() => void run('ai-connect')}>ChatGPT 연결 · 새로고침</button>{connection.authUrl && <a className="login-link" href={connection.authUrl} target="_blank" rel="noreferrer">ChatGPT로 로그인 ↗</a>}<span>{connection.message}{connection.plan ? ` · ${connection.plan}` : ''}</span></div>
    <p className="help">별도 API 키를 사용하지 않습니다. ChatGPT의 Codex 사용 한도를 소모하며 한도 도달 시 대기합니다. 문체는 ‘나의 문체’ 화면에서 분석·확정한 뒤 선택할 수 있습니다.</p>
    {connection.limits?.map((limit, index) => <small className="usage" key={index}>{limit.name} · {limit.used}% 사용{limit.resetsAt ? ` · 갱신 ${new Date(limit.resetsAt*1000).toLocaleString('ko-KR')}` : ''}</small>)}
    {connection.state === 'connected' && <><label>적용할 문체<select value={profileId} onChange={e=>setProfileId(e.target.value)}><option value="">기본 문체</option>{profiles.filter(p=>p.kind==='common'||p.kind===draft.kind).map(p=><option key={p.id} value={p.id}>{p.name} · v{p.version}</option>)}</select></label><label>생성 모델<select value={model} onChange={e => setModel(e.target.value)}>{connection.models.map(m => <option key={m.id} value={m.id}>{m.name}{m.images ? ' · 사진 지원' : ' · 텍스트'}</option>)}</select></label><details><summary>선택한 구간만 다시 쓰기</summary><label>본문에서 바꿀 구간<textarea rows={3} maxLength={20000} value={selection} onChange={e => setSelection(e.target.value)} placeholder="본문에서 한 번만 등장하는 구간을 그대로 복사하세요." /></label><label>수정 요청<textarea rows={2} maxLength={4000} value={instruction} onChange={e => setInstruction(e.target.value)} placeholder="예: 초보자도 이해하기 쉽게 설명해줘." /></label></details><button className="primary" disabled={busy || dirty || !draft.id || !online || active || !model} onClick={() => void run('ai-generate', { id: draft.id, model, selection, instruction, profileId })}>{selection ? '선택 구간 재작성' : draft.kind === 'project' ? '요약·사진으로 초안 생성' : draft.kind === 'technical' ? '기술 글 초안 생성' : 'PS 해설 초안 생성'}</button>{(dirty || !draft.id) && <p className="help">변경한 원고를 먼저 저장하세요.</p>}</>}
    {message && <p role="status" className="notice">{message}</p>}
    {own.map(job => <div className="ai-result" key={job.id}><div className="section-heading"><h3>{job.selection ? '부분 재작성' : job.draft.kind === 'ps' ? 'PS 해설' : job.draft.kind === 'technical' ? '기술 초안' : '프로젝트 초안'} · 원고 v{job.draft.version}</h3><small>{new Date(job.createdAt).toLocaleString('ko-KR')}</small></div><p>{job.step}</p><small>{job.style ? `${job.style.name} · 문체 v${job.style.version} · 예시 ${job.style.examples.length}개` : '기본 문체'}</small>{job.usage && <small>반환된 사용량: 입력 {job.usage.input} · 출력 {job.usage.output} · 총 {job.usage.total} 토큰 (청구 금액 아님)</small>}{job.state === 'succeeded' && !job.usage && <small>사용량 정보가 반환되지 않았습니다.</small>}
      {job.output && <><h3>{job.output.title}</h3><ul>{job.output.outline.map((line,i) => <li key={i}>{line}</li>)}</ul>{job.output.warnings.length > 0 && <div className="notice"><strong>확인할 내용</strong><ul>{job.output.warnings.map((line,i) => <li key={i}>{line}</li>)}</ul></div>}<label>생성된 본문<textarea readOnly rows={10} value={job.output.markdown} /></label>{job.output.captions.map((caption,i) => <p key={caption.id}>사진 {i+1}: {caption.caption}</p>)}<button disabled={busy || dirty || !!job.appliedVersion || draft.version !== job.draft.version} onClick={async () => { const value = await run('ai-apply', { id: job.id }); if (value) applied(value); }}>{job.appliedVersion ? `v${job.appliedVersion}에 적용됨` : '검토한 결과를 원고에 적용'}</button><button onClick={() => void navigator.clipboard.writeText(job.output!.markdown).then(() => setMessage('본문을 복사했습니다.')).catch(() => setMessage('본문을 직접 선택해 복사해주세요.'))}>본문 복사</button>{!job.appliedVersion && draft.version !== job.draft.version && <p className="help">원고가 변경되어 자동 적용할 수 없습니다. 결과를 복사하거나 최신 버전으로 생성하세요.</p>}</>}
      {['queued','running'].includes(job.state) && <button disabled={busy || job.cancel} onClick={() => void run('ai-cancel', { id: job.id })}>생성 취소</button>}{job.state === 'failed' && job.attempts < 2 && <button disabled={busy || !online} onClick={() => void run('ai-retry', { id: job.id })}>한 번 재시도</button>}
    </div>)}
    {own.filter(j=>j.output).length>1 && <details><summary>생성 결과 나란히 비교</summary><div className="style-compare">{[{value:left,set:setLeft},{value:right,set:setRight}].map((side,index)=><div key={index}><select aria-label={`비교 결과 ${index+1}`} value={side.value} onChange={e=>side.set(e.target.value)}><option value="">결과 선택</option>{own.filter(j=>j.output).map(j=><option key={j.id} value={j.id}>{j.style?.name||'기본 문체'} · 원고 v{j.draft.version} · {new Date(j.createdAt).toLocaleTimeString('ko-KR')}</option>)}</select><textarea readOnly rows={14} value={own.find(j=>j.id===side.value)?.output?.markdown||''}/></div>)}</div><p className="help">같은 원고 버전과 모델로 각각 생성하면 문체 차이를 비교하기 좋습니다. 표현에는 생성마다 차이가 있을 수 있습니다.</p></details>}
    {draft.id && <details><summary onClick={() => { void request('versions', { id: draft.id }).then(setVersions).catch(() => setMessage('버전 목록을 불러오지 못했습니다.')); }}>저장된 원고 버전 확인</summary>{versions.map(v => <details key={v.version}><summary>v{v.version} · {v.title || '제목 없음'}</summary><textarea readOnly rows={8} value={v.markdown} /></details>)}</details>}
  </section>;
}
