'use client';
import { useEffect, useState } from 'react';
import type { Draft } from '../lib/model';
import type { AiConnection, AiJob } from '../lib/ai-model';

type Props = { draft: Draft; dirty: boolean; online: boolean; connection: AiConnection; jobs: AiJob[]; request: (action: string, values?: object) => Promise<any>; refresh: () => Promise<void>; applied: (draft: Draft) => void; lock: (busy: boolean) => void };
export function AiPanel({ draft, dirty, online, connection, jobs, request, refresh, applied, lock }: Props) {
  const [model, setModel] = useState(''); const [selection, setSelection] = useState(''); const [instruction, setInstruction] = useState(''); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false); const [versions, setVersions] = useState<Draft[]>([]);
  useEffect(() => { if (!connection.models.some(m => m.id === model)) setModel((connection.models.find(m => m.isDefault) || connection.models[0])?.id || ''); }, [connection.models, model]);
  useEffect(() => { setSelection(''); setInstruction(''); setVersions([]); }, [draft.id]);
  async function run(action: string, values: object = {}) { setBusy(true); lock(true); setMessage(''); try { const value = await request(action, values); await refresh(); return value; } catch (error) { setMessage(error instanceof Error ? error.message : '요청 실패'); } finally { setBusy(false); lock(false); } }
  const own = jobs.filter(j => j.draft.id === draft.id);
  const active = own.some(j => ['queued','running'].includes(j.state));
  return <section className="panel ai-panel"><div className="section-heading"><h2>ChatGPT로 프로젝트 초안 만들기</h2><span className="tag">P2</span></div>
    <p>저장한 요약과 사진을 보내 개요·본문·사진 설명을 만듭니다. 결과를 검토한 뒤 원고에 적용하세요.</p>
    <div className="button-row"><button disabled={busy || !online || connection.state === 'connecting' || active} onClick={() => void run('ai-connect')}>ChatGPT 연결 · 새로고침</button>{connection.authUrl && <a className="login-link" href={connection.authUrl} target="_blank" rel="noreferrer">ChatGPT로 로그인 ↗</a>}<span>{connection.message}{connection.plan ? ` · ${connection.plan}` : ''}</span></div>
    <p className="help">별도 API 키를 사용하지 않습니다. ChatGPT의 Codex 사용 한도를 소모하며 한도 도달 시 대기합니다. 기존 블로그 문체 분석은 다음 단계에서 제공됩니다.</p>
    {connection.limits?.map((limit, index) => <small className="usage" key={index}>{limit.name} · {limit.used}% 사용{limit.resetsAt ? ` · 갱신 ${new Date(limit.resetsAt*1000).toLocaleString('ko-KR')}` : ''}</small>)}
    {connection.state === 'connected' && <><label>생성 모델<select value={model} onChange={e => setModel(e.target.value)}>{connection.models.map(m => <option key={m.id} value={m.id}>{m.name}{m.images ? ' · 사진 지원' : ' · 텍스트'}</option>)}</select></label><details><summary>선택한 구간만 다시 쓰기</summary><label>본문에서 바꿀 구간<textarea rows={3} maxLength={20000} value={selection} onChange={e => setSelection(e.target.value)} placeholder="본문에서 한 번만 등장하는 구간을 그대로 복사하세요." /></label><label>수정 요청<textarea rows={2} maxLength={4000} value={instruction} onChange={e => setInstruction(e.target.value)} placeholder="예: 초보자도 이해하기 쉽게 설명해줘." /></label></details><button className="primary" disabled={busy || dirty || !draft.id || draft.kind !== 'project' || !online || active || !model} onClick={() => void run('ai-generate', { id: draft.id, model, selection, instruction })}>{selection ? '선택 구간 재작성' : '요약·사진으로 초안 생성'}</button>{(dirty || !draft.id) && <p className="help">변경한 원고를 먼저 저장하세요.</p>}{draft.kind !== 'project' && <p className="help">P2는 프로젝트 글 생성을 지원합니다.</p>}</>}
    {message && <p role="status" className="notice">{message}</p>}
    {own.map(job => <div className="ai-result" key={job.id}><div className="section-heading"><h3>{job.selection ? '부분 재작성' : '프로젝트 초안'} · 원고 v{job.draft.version}</h3><small>{new Date(job.createdAt).toLocaleString('ko-KR')}</small></div><p>{job.step}</p>{job.usage && <small>반환된 사용량: 입력 {job.usage.input} · 출력 {job.usage.output} · 총 {job.usage.total} 토큰 (청구 금액 아님)</small>}{job.state === 'succeeded' && !job.usage && <small>사용량 정보가 반환되지 않았습니다.</small>}
      {job.output && <><h3>{job.output.title}</h3><ul>{job.output.outline.map((line,i) => <li key={i}>{line}</li>)}</ul>{job.output.warnings.length > 0 && <div className="notice"><strong>확인할 내용</strong><ul>{job.output.warnings.map((line,i) => <li key={i}>{line}</li>)}</ul></div>}<label>생성된 본문<textarea readOnly rows={10} value={job.output.markdown} /></label>{job.output.captions.map((caption,i) => <p key={caption.id}>사진 {i+1}: {caption.caption}</p>)}<button disabled={busy || dirty || !!job.appliedVersion || draft.version !== job.draft.version} onClick={async () => { const value = await run('ai-apply', { id: job.id }); if (value) applied(value); }}>{job.appliedVersion ? `v${job.appliedVersion}에 적용됨` : '검토한 결과를 원고에 적용'}</button><button onClick={() => void navigator.clipboard.writeText(job.output!.markdown).then(() => setMessage('본문을 복사했습니다.')).catch(() => setMessage('본문을 직접 선택해 복사해주세요.'))}>본문 복사</button>{!job.appliedVersion && draft.version !== job.draft.version && <p className="help">원고가 변경되어 자동 적용할 수 없습니다. 결과를 복사하거나 최신 버전으로 생성하세요.</p>}</>}
      {['queued','running'].includes(job.state) && <button disabled={busy || job.cancel} onClick={() => void run('ai-cancel', { id: job.id })}>생성 취소</button>}{job.state === 'failed' && job.attempts < 2 && <button disabled={busy || !online} onClick={() => void run('ai-retry', { id: job.id })}>한 번 재시도</button>}
    </div>)}
    {draft.id && <details><summary onClick={() => { void request('versions', { id: draft.id }).then(setVersions).catch(() => setMessage('버전 목록을 불러오지 못했습니다.')); }}>저장된 원고 버전 확인</summary>{versions.map(v => <details key={v.version}><summary>v{v.version} · {v.title || '제목 없음'}</summary><textarea readOnly rows={8} value={v.markdown} /></details>)}</details>}
  </section>;
}
