'use client';
import { useEffect, useState } from 'react';
import type { Draft } from '../lib/model';
import { emptyMaterial, type Material, type Reference } from '../lib/material';
import type { CodeCheck } from '../services/code-check';

type Props = { draft: Draft; references: Reference[]; checks: CodeCheck[]; disabled: boolean; dirty: boolean; online: boolean; edit: (patch: Partial<Draft>) => void; request: (action: string, values?: object) => Promise<any>; refresh: () => Promise<void> };
export function MaterialPanel({ draft, references, checks, disabled, dirty, online, edit, request, refresh }: Props) {
  const [url, setUrl] = useState(''); const [title, setTitle] = useState(''); const [text, setText] = useState(''); const [busy, setBusy] = useState(false); const [message, setMessage] = useState('');
  useEffect(() => { setUrl(''); setTitle(''); setText(''); setMessage(''); }, [draft.id]);
  if (!['technical', 'ps', 'information'].includes(draft.kind)) return null;
  const material = draft.material || emptyMaterial();
  const change = (patch: Partial<Material>) => edit({ material: { ...material, ...patch } });
  async function run(action: string, values: object = {}) {
    setBusy(true); setMessage('');
    try { const result = await request(action, values); await refresh(); setMessage(action === 'code-check' ? '검증을 요청했습니다. 저장한 코드와 예제만 실행합니다.' : '자료를 보관했습니다. 아래 목록에서 이 원고에 사용할 자료를 선택하세요.'); return result; }
    catch (error) { setMessage(error instanceof Error ? error.message : '요청 실패'); }
    finally { setBusy(false); }
  }
  return <section className="panel material-panel"><h2>{draft.kind !== 'ps' ? (draft.kind === 'information' ? '정보 글 참고 자료' : '기술 글 자료') : 'PS 문제와 검증'}</h2><fieldset disabled={disabled || busy} style={{ border: 0, padding: 0, minWidth: 0 }}>
    {draft.kind !== 'ps' ? <><label>{draft.kind === 'information' ? '정보 주제' : '기술 주제'}<input maxLength={500} value={material.topic} onChange={e => change({ topic: e.target.value })} placeholder="예: Python 리스트와 스택" /></label><p className="help">기술 글은 요약에 설명 범위·독자 수준을 20자 이상 적고, 정보 글은 위의 독자·범위를 입력하세요.</p></> : <><label>문제 본문<textarea rows={6} maxLength={20000} value={material.problem} onChange={e => change({ problem: e.target.value })} placeholder="입출력 형식을 포함해 입력하세요. URL에서 가져온 본문은 아래에서 확인 후 복사할 수 있습니다." /></label><label>제약 조건<textarea rows={3} maxLength={5000} value={material.constraints} onChange={e => change({ constraints: e.target.value })} placeholder="N의 범위, 시간·메모리 제한, 값의 범위" /></label><label>풀이 언어<input maxLength={50} value={material.language} onChange={e => change({ language: e.target.value })} /></label></>}
    <label>{draft.kind !== 'ps' ? '나의 해석 · 궁금한 점' : '나의 접근 과정'}<textarea rows={3} maxLength={10000} value={material.interpretation} onChange={e => change({ interpretation: e.target.value })} /></label>
    <details><summary>참고 URL 가져오기 · 본문 붙여넣기</summary><p className="help">Python·MDN·MySQL·PostgreSQL·Oracle·Linux·Microsoft·Docker·Rust·Go·Node.js 공식 문서, 한국관광공사·대한민국 정책브리핑과 백준·프로그래머스·AtCoder·Codeforces를 지원합니다. 접근 실패나 다른 사이트는 본문을 붙여넣으세요.</p><label>참고 URL<input value={url} maxLength={2000} onChange={e => setUrl(e.target.value)} placeholder="https://docs.python.org/3/tutorial/datastructures.html" /></label><button onClick={() => void run('reference-fetch', { url })}>URL 본문 가져오기</button><label>자료 제목<input value={title} maxLength={300} onChange={e => setTitle(e.target.value)} /></label><label>자료 본문<textarea rows={5} maxLength={20000} value={text} onChange={e => setText(e.target.value)} /></label><button onClick={() => void run('reference-paste', { source: { title, url, text } })}>붙여넣은 자료 보관</button></details>
    <p className="help">최대 5개를 선택하세요. 자료는 생성 시점의 내용으로 보관됩니다. 접근 확인은 사실 검증 완료를 뜻하지 않습니다.</p>
    {references.map(source => <details key={source.id} data-reference-id={source.id}><summary><input aria-label={`자료 선택 ${source.title}`} type="checkbox" checked={material.referenceIds.includes(source.id)} disabled={!material.referenceIds.includes(source.id) && material.referenceIds.length >= 5} onChange={e => change({ referenceIds: e.target.checked ? [...material.referenceIds, source.id] : material.referenceIds.filter(id => id !== source.id) })} /> {source.title} · {source.method === 'pasted' ? '붙여넣기 · 원본 미확인' : source.official ? '공식 도메인 접근 확인 · 사실 미대조' : '문제 사이트 접근 확인 · 사실 미대조'}</summary><p>{source.url} · {new Date(source.checkedAt).toLocaleString('ko-KR')}</p><textarea readOnly rows={6} value={source.text} />{draft.kind === 'ps' && <button disabled={!!material.problem.trim()} onClick={() => change({ problem: source.text })}>빈 문제 본문에 가져오기</button>}</details>)}
    {draft.kind === 'ps' && <><label>검토·실행할 코드<textarea rows={8} maxLength={20000} value={material.code} onChange={e => change({ code: e.target.value })} placeholder="본인 코드 또는 생성된 코드. 원고 본문과 별도로 저장됩니다." /></label><button onClick={() => { const blocks = [...draft.markdown.matchAll(/```(?:python|py)\s*\n([\s\S]*?)```/g)]; if (blocks.length !== 1) { setMessage('본문에 Python 코드 블록이 정확히 하나 있어야 합니다. 원하는 코드를 직접 복사하세요.'); return; } if (material.code.trim()) { setMessage('기존 코드가 있습니다. 교체할 코드를 직접 붙여넣어 주세요.'); return; } change({ code: blocks[0][1] }); }}>본문의 Python 코드 가져오기</button><h3>예제 · 경계 사례</h3>{material.cases.map((example, index) => <div className="ai-result" key={index}><label>사례 {index + 1} 유형<select value={example.kind} onChange={e => change({ cases: material.cases.map((c, i) => i === index ? { ...c, kind: e.target.value as 'example' | 'edge' } : c) })}><option value="example">문제 예제</option><option value="edge">경계 사례</option></select></label><label>입력 {index + 1}<textarea rows={2} maxLength={5000} value={example.input} onChange={e => change({ cases: material.cases.map((c, i) => i === index ? { ...c, input: e.target.value } : c) })} /></label><label>기대 출력 {index + 1}<textarea rows={2} maxLength={5000} value={example.expected} onChange={e => change({ cases: material.cases.map((c, i) => i === index ? { ...c, expected: e.target.value } : c) })} /></label><button onClick={() => change({ cases: material.cases.filter((_, i) => i !== index) })}>사례 제외</button></div>)}<button disabled={material.cases.length >= 5} onClick={() => change({ cases: [...material.cases, { input: '', expected: '', kind: 'example' }] })}>예제 추가</button><button disabled={dirty || !draft.id || !online || checks.some(c => ['queued', 'running'].includes(c.state))} onClick={() => void run('code-check', { id: draft.id })}>저장한 Python 코드 예제 검증</button><p className="help">Docker와 python:3.12-slim 이미지가 준비되어야 실행합니다. 네트워크·호스트 파일 접근 없이 시간·메모리·출력을 제한합니다. 다른 언어는 해설 생성만 지원합니다. 본문 코드와 실행 코드가 같은지 직접 확인하세요.</p>{checks.filter(c => c.draftId === draft.id).map(c => <div key={c.id} className="notice"><strong>원고 v{c.version} · {c.state === 'passed' ? '입력 사례 일치' : c.state === 'failed' ? '실패' : c.state === 'unavailable' ? '미실행' : '대기·진행 중'}</strong><p>{c.message}</p>{(dirty || c.version !== draft.version) && <p>원고가 변경되었습니다. 현재 원고의 검증 결과로 사용할 수 없습니다.</p>}{c.results.map((r, i) => <details key={i}><summary>사례 {i + 1} · {r.passed ? '일치' : '불일치 또는 실행 실패'}</summary><pre>{r.actual || '(출력 없음)'}</pre></details>)}</div>)}</>}
    </fieldset>{message && <p role="status" className="notice">{message}</p>}</section>;
}
