'use client';
import { useCallback, useEffect, useRef, useState } from 'react';
import type { Asset, Draft, Job, Settings } from '../lib/model';
import { jobLabels } from '../lib/model';
import { AiPanel } from './ai-panel';
import { StylePanel, type StyleState } from './style-panel';
import type { AiConnection, AiJob } from '../lib/ai-model';

type State = { styles: StyleState; ai: { connection: AiConnection; jobs: AiJob[] }; drafts: Draft[]; assets: Asset[]; jobs: Job[]; settings: Settings; workerOnline: boolean };
const emptyDraft = (): Draft => ({ id: '', version: 0, title: '', kind: 'project', summary: '', markdown: '', category: '테스트', images: [], cover: null, updatedAt: '' });
async function api(action: string, values: object = {}) {
  const response = await fetch('/api/app', { method: 'POST', headers: { 'Content-Type': 'application/json', 'X-Tstory-Request': 'local-web' }, body: JSON.stringify({ action, ...values }) });
  const data = await response.json(); if (!response.ok) throw new Error(data.error); return data;
}
export default function Home() {
  const [state, setState] = useState<State>(); const [tab, setTab] = useState('drafts'); const [draft, setDraft] = useState<Draft>(emptyDraft); const [dirty, setDirty] = useState(false);
  const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false); const [html, setHtml] = useState(''); const [blog, setBlog] = useState(''); const [confirmPublish, setConfirmPublish] = useState(false);
  const fileRef = useRef<HTMLInputElement>(null); const folderRef = useRef<HTMLInputElement>(null); const libraryRef = useRef<HTMLInputElement>(null);
  const refresh = useCallback(async () => { const response = await fetch('/api/app', { cache: 'no-store' }); if (!response.ok) throw new Error('로컬 앱 연결을 확인하세요.'); setState(await response.json()); }, []);
  useEffect(() => { void refresh().catch(error => setMessage(error.message)); const timer = setInterval(() => void refresh().catch(() => {}), 2500); return () => clearInterval(timer); }, [refresh]);
  useEffect(() => { if (state?.settings.blog) setBlog(state.settings.blog); }, [state?.settings.blog]);
  useEffect(() => { const handler = (event: BeforeUnloadEvent) => { if (dirty) event.preventDefault(); }; window.addEventListener('beforeunload', handler); return () => window.removeEventListener('beforeunload', handler); }, [dirty]);
  useEffect(() => { let active = true; const timer = setTimeout(() => { void api('preview', { markdown: draft.markdown }).then(value => { if (active) setHtml(value.html); }).catch(() => {}); }, 300); return () => { active = false; clearTimeout(timer); }; }, [draft.markdown]);
  const edit = (value: Partial<Draft>) => { if (busy) return; setDraft(previous => ({ ...previous, ...value })); setDirty(true); setConfirmPublish(false); };
  async function perform(fn: () => Promise<void>) { setBusy(true); setMessage(''); try { await fn(); await refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : '작업 실패'); } finally { setBusy(false); } }
  const open = (value: Draft) => { if (busy) return; if (dirty && !window.confirm('저장하지 않은 변경을 버리고 원고를 열까요?')) return; setDraft(value); setDirty(false); setConfirmPublish(false); setTab('editor'); };
  async function upload(files: FileList | null, library: boolean) {
    if (!files?.length) return;
    const selected = Array.from(files).filter(file => /\.(png|jpe?g|webp)$/i.test(file.name));
    await perform(async () => {
      if (!selected.length) throw new Error('PNG·JPEG·WebP 사진을 선택하세요.');
      if (!library && draft.images.length + selected.length > 20) throw new Error('원고당 사진은 최대 20장입니다.');
      for (const file of selected) {
        const form = new FormData(); form.set('file', file); form.set('library', String(library));
        const response = await fetch('/api/assets', { method: 'POST', headers: { 'X-Tstory-Request': 'local-web' }, body: form }); const asset = await response.json(); if (!response.ok) throw new Error(`${file.name}: ${asset.error}`);
        if (!library) { setDraft(previous => ({ ...previous, images: [...previous.images, { id: asset.id, caption: '' }], cover: previous.cover || asset.id })); setDirty(true); }
      }
      setMessage(`${selected.length}장의 사진을 가져왔습니다.${library ? '' : ' 원고를 저장해주세요.'}`);
    });
  }
  const image = (id: string) => state?.assets.find(asset => asset.id === id);
  const headings: Record<string, string> = { drafts: '나의 원고', editor: draft.id ? '원고 다듬기' : '새로운 이야기', library: '표지 라이브러리', jobs: '작업 내역', settings: '블로그 연결', style: '나의 문체' };
  return <div className="app-shell">
    <aside><a className="brand" href="/">글담<span>TISTORY STUDIO</span></a><div className="workspace-label">MY WORKSPACE</div><nav>{[['drafts','▤','나의 원고'],['style','✎','나의 문체'],['library','▧','표지 라이브러리'],['jobs','◷','작업 내역'],['settings','⚙','블로그 연결']].map(([key, icon, label]) => <button key={key} className={tab === key || (key === 'drafts' && tab === 'editor') ? 'nav-active' : ''} onClick={() => setTab(key)}><span>{icon}</span>{label}</button>)}</nav><div className="local-card"><span className={`dot ${state?.workerOnline ? 'online' : ''}`} />{state?.workerOnline ? '로컬 실행기 연결됨' : '실행기 연결 대기'}<small>자료는 이 컴퓨터에 저장됩니다.</small></div><div className="phase">P3 · PERSONAL STYLE</div></aside>
    <main><header><div><div className="eyebrow">WRITE SOMETHING WORTH SHARING</div><h1>{headings[tab]}</h1></div><span className="private-badge">● 비공개 저장 모드</span></header>
      {message && <div className="notice" role="status">{message}<button aria-label="알림 닫기" onClick={() => setMessage('')}>×</button></div>}
      {!state ? <div className="panel">작업 공간을 불러오는 중…</div> : <>
        {tab === 'drafts' && <><div className="hero"><div className="eyebrow">YOUR NEXT STORY STARTS HERE</div><h2>기록을 모으고,<br />하나의 글로 완성하세요.</h2><p>프로젝트의 과정부터 작은 배움까지.<br />사진과 생각을 모아 나만의 티스토리 원고를 준비해보세요.</p><button className="primary" onClick={() => open(emptyDraft())}>＋ 새 원고 작성</button><div className="hero-decoration" aria-hidden="true">Aa<span>생각을 담는 공간</span></div></div><div className="section-heading"><h2>저장한 원고 <span>{state.drafts.length}</span></h2><p>AI 초안 · Markdown 편집</p></div>{!state.drafts.length ? <div className="empty"><span>✎</span><h3>첫 번째 원고를 기다리고 있어요</h3><p>제목과 본문을 쓰고 사진을 더해보세요.</p></div> : <div className="draft-grid">{state.drafts.map(item => <button className="draft-card" key={item.id} onClick={() => open(item)}>{item.cover ? <img src={`/api/assets/${item.cover}`} alt="원고 표지" /> : <div className="cover-placeholder">{item.kind === 'ps' ? '{ }' : 'Aa'}</div>}<div><small>{item.kind.toUpperCase()} · {item.category || '카테고리 미지정'}</small><h3>{item.title || '제목 없는 원고'}</h3><p>{item.summary || item.markdown.slice(0, 100) || '아직 작성한 내용이 없습니다.'}</p><span>v{item.version} · {new Date(item.updatedAt).toLocaleDateString('ko-KR')}</span></div></button>)}</div>}</>}
        {tab === 'editor' && <><div className="editor-toolbar"><span>{dirty ? '● 저장하지 않은 변경' : draft.id ? `저장됨 · 버전 ${draft.version}` : '새 원고'} </span><div><button disabled={busy} onClick={() => void perform(async () => { const saved = await api('save', { draft }); setDraft(saved); setDirty(false); setMessage('원고를 저장했습니다.'); })}>원고 저장</button><button className="primary" disabled={busy || dirty || !draft.id || !state.workerOnline} onClick={() => setConfirmPublish(true)}>비공개 전송</button></div></div>
          {confirmPublish && <div className="publish-review"><h3>이 원고를 비공개로 저장할까요?</h3><p>{draft.title} · 버전 {draft.version}<br />{state.settings.blog} → {draft.category} · 사진 {draft.images.length}장</p><button className="primary" disabled={busy} onClick={() => void perform(async () => { await api('publish', { id: draft.id }); setConfirmPublish(false); setTab('jobs'); })}>확인하고 전송</button><button onClick={() => setConfirmPublish(false)}>돌아가기</button></div>}
          <AiPanel profiles={state.styles.profiles} lock={setBusy} draft={draft} dirty={dirty || busy} online={state.workerOnline} connection={state.ai.connection} jobs={state.ai.jobs} request={api} refresh={refresh} applied={value => { setDraft(value); setDirty(false); setConfirmPublish(false); }} />
          <div className="editor-columns"><section className="panel"><div className="field-row"><label>글 유형<select value={draft.kind} onChange={event => edit({ kind: event.target.value as Draft['kind'] })}><option value="project">프로젝트</option><option value="technical">기술</option><option value="ps">PS 문제</option></select></label><label>카테고리<select value={draft.category} onChange={event => edit({ category: event.target.value })}><option value={draft.category}>{draft.category || '선택하세요'}</option>{state.settings.categories.filter(c => c !== draft.category).map(category => <option key={category}>{category}</option>)}</select></label></div><label>제목<input maxLength={150} placeholder="어떤 이야기를 기록할까요?" value={draft.title} onChange={event => edit({ title: event.target.value })} /></label><label>요약 · 작성 메모<textarea rows={3} placeholder="프로젝트 배경, 배운 점, 꼭 담고 싶은 내용을 적어주세요." value={draft.summary} onChange={event => edit({ summary: event.target.value })} /></label><label>본문 <small>Markdown · 코드 블록 · 표 지원</small><textarea className="markdown" rows={18} placeholder={'## 시작하며\n\n직접 작성하거나 요약과 사진으로 AI 초안을 생성하세요.'} value={draft.markdown} onChange={event => edit({ markdown: event.target.value })} /></label><p className="help">요약은 작성 메모로 보관되며 본문에 자동 삽입되지 않습니다. 외부 이미지와 HTML 스크립트는 본문에서 제외됩니다.</p></section>
          <section className="panel preview-panel"><div className="section-heading"><h2>미리보기</h2><span className="tag">비공개</span></div><h2 className="preview-title">{draft.title || '제목이 여기에 표시됩니다'}</h2><article dangerouslySetInnerHTML={{ __html: html }} />{draft.images.map(item => <figure key={item.id}><img src={`/api/assets/${item.id}`} alt={item.caption || image(item.id)?.name || '원고 사진'} /><figcaption>{item.caption}</figcaption></figure>)}<p className="help">사진은 본문 아래에 순서대로 첨부됩니다. 블로그 스킨에 따라 표시가 달라질 수 있습니다.</p></section></div>
          <section className="panel photos"><div className="section-heading"><h2>원고 사진 <span>{draft.images.length}/20</span></h2><div><button disabled={busy} onClick={() => fileRef.current?.click()}>사진 선택</button><button disabled={busy} onClick={() => folderRef.current?.click()}>폴더 가져오기</button></div></div><input hidden ref={fileRef} type="file" multiple accept="image/png,image/jpeg,image/webp" onChange={event => { void upload(event.target.files, false); event.target.value = ''; }} /><input hidden ref={folderRef} type="file" multiple {...{ webkitdirectory: '' }} onChange={event => { void upload(event.target.files, false); event.target.value = ''; }} /><p className="help">PNG·JPEG·WebP · 장당 10MB 이하 · 폴더에서는 사진만 가져옵니다.</p>{draft.images.map((item, index) => <div className="photo-row" key={item.id}><img src={`/api/assets/${item.id}`} alt={image(item.id)?.name || '사진'} /><div><strong>{index + 1}. {image(item.id)?.name}</strong><input aria-label={`사진 ${index + 1} 설명`} value={item.caption} placeholder="사진 설명" maxLength={500} onChange={event => edit({ images: draft.images.map(i => i.id === item.id ? { ...i, caption: event.target.value } : i) })} /></div><button className={draft.cover === item.id ? 'selected' : ''} onClick={() => edit({ cover: item.id })}>{draft.cover === item.id ? '✓ 대표' : '대표로'}</button><button aria-label={`사진 ${index + 1} 위로`} disabled={index === 0} onClick={() => { const images = [...draft.images]; [images[index-1], images[index]] = [images[index], images[index-1]]; edit({ images }); }}>↑</button><button aria-label={`사진 ${index + 1} 아래로`} disabled={index === draft.images.length - 1} onClick={() => { const images = [...draft.images]; [images[index+1], images[index]] = [images[index], images[index+1]]; edit({ images }); }}>↓</button><button onClick={() => edit({ images: draft.images.filter(i => i.id !== item.id), cover: draft.cover === item.id ? null : draft.cover })}>제외</button></div>)}{state.assets.some(a => a.library) && <label>라이브러리에서 표지 가져오기<select value="" onChange={event => { const id = event.target.value; if (id && !draft.images.some(i => i.id === id)) edit({ images: [...draft.images, { id, caption: '' }], cover: id }); }}><option value="">표지 선택</option>{state.assets.filter(a => a.library && !draft.images.some(i => i.id === a.id)).map(a => <option key={a.id} value={a.id}>{a.name}</option>)}</select></label>}</section></>}
        {tab === 'style' && <StylePanel data={state.styles} connection={state.ai.connection} online={state.workerOnline} drafts={state.drafts} request={api} refresh={refresh} />}
        {tab === 'library' && <><div className="section-heading"><p>여러 글에서 다시 사용할 표지 사진을 모아두세요.</p><button className="primary" disabled={busy} onClick={() => libraryRef.current?.click()}>＋ 표지 추가</button></div><input ref={libraryRef} hidden type="file" multiple accept="image/png,image/jpeg,image/webp" onChange={event => { void upload(event.target.files, true); event.target.value = ''; }} /><div className="draft-grid">{state.assets.filter(a => a.library).map(a => <div className="draft-card" key={a.id}><img src={`/api/assets/${a.id}`} alt={a.name} /><div><h3>{a.name}</h3><p>{Math.round(a.size / 1024)} KB · 원고 사진에서 선택할 수 있어요</p></div></div>)}</div>{!state.assets.some(a => a.library) && <div className="empty"><span>▧</span><h3>자주 쓰는 표지를 한곳에</h3><p>표지를 추가하면 원고마다 다시 업로드할 필요가 없어요.</p></div>}</>}
        {tab === 'settings' && <section className="panel settings"><h2>티스토리 계정 연결</h2><p>전용 Chrome에서 직접 로그인하면 이 컴퓨터에서 연결을 재사용합니다.</p><label>블로그 주소<input value={blog} onChange={event => setBlog(event.target.value)} placeholder="https://my-blog.tistory.com" /></label><div className="button-row"><button disabled={busy || blog === state.settings.blog} onClick={() => void perform(async () => { await api('settings', { blog }); setMessage('블로그 주소를 저장했습니다.'); })}>주소 저장</button><button className="primary" disabled={busy || !state.workerOnline} onClick={() => void perform(async () => { const job = await api('connect'); if (job.state === 'needs_login') await api('resume', { id: job.id }); setTab('jobs'); })}>로그인 확인 · 카테고리 새로고침</button></div><dl><dt>연결 상태</dt><dd>{state.settings.connection}</dd><dt>마지막 확인</dt><dd>{state.settings.checkedAt ? new Date(state.settings.checkedAt).toLocaleString('ko-KR') : '아직 확인하지 않았습니다'}</dd><dt>카테고리</dt><dd>{state.settings.categories.join(' · ') || '연결 후 불러옵니다'}</dd></dl><p className="help">로그인이 필요하면 열린 Chrome에서 로그인한 뒤 작업 내역의 ‘재개’를 눌러주세요. 비밀번호는 앱에 입력하지 않습니다.</p></section>}
        {tab === 'jobs' && <><p className="intro">브라우저 작업의 진행 상태와 저장 결과를 확인하세요.</p>{!state.workerOnline && <div className="notice">실행기가 꺼져 있습니다. 터미널에서 npm run dev로 웹앱과 실행기를 함께 시작하세요.</div>}{!state.jobs.length && <div className="empty"><span>◷</span><h3>아직 실행한 작업이 없어요</h3><p>블로그를 연결하거나 원고를 비공개로 전송하면 여기에 표시됩니다.</p></div>}{state.jobs.map(job => <div className="panel job" key={job.id}><div><span className={`state state-${job.state}`}>{jobLabels[job.state] || job.state}</span><small>{new Date(job.createdAt).toLocaleString('ko-KR')}</small><h3>{job.kind === 'connect' ? '블로그 연결 · 카테고리 새로고침' : job.snapshot.draft?.title}</h3><p>{job.step}</p>{job.kind === 'publish' && <small>{job.snapshot.draft?.category} · 버전 {job.snapshot.draft?.version} · 비공개</small>}{job.result && /^https:\/\/[a-z0-9-]+\.tistory\.com\//.test(job.result) && <a href={job.result} target="_blank" rel="noreferrer">저장된 글 보기 ↗</a>}{job.state === 'unknown' && <p>저장 요청 후 결과를 확정하지 못했습니다. 중복 전송하지 말고 <a href={`${job.snapshot.blog}/manage/posts`} target="_blank" rel="noreferrer">티스토리 글 관리</a>에서 확인해주세요.</p>}</div><div className="job-actions">{job.result && ['needs_attention','succeeded'].includes(job.state) && <button disabled={busy || !state.workerOnline} onClick={() => void perform(async () => { await api('verify', { id: job.id }); })}>저장 결과 다시 확인</button>}{['needs_login','failed'].includes(job.state) && <button disabled={busy || !state.workerOnline} onClick={() => void perform(async () => { await api('resume', { id: job.id }); })}>{job.state === 'needs_login' ? '로그인 완료 · 재개' : '재시도'}</button>}{['queued','needs_login','failed'].includes(job.state) && <button disabled={busy} onClick={() => void perform(async () => { await api('cancel', { id: job.id }); })}>취소</button>}</div></div>)}</>}
      </>}
      <footer>글담 <span>당신의 기록이 다음 이야기의 시작이 되도록.</span></footer>
    </main>
  </div>;
}
