'use client';
import { useState,useEffect } from 'react';
import type { StyleSource,StyleProfile,StyleJob,StyleKind } from '../lib/style-model';
import type { AiConnection } from '../lib/ai-model';
import type { Draft } from '../lib/model';
export type StyleState={sources:StyleSource[];profiles:StyleProfile[];jobs:StyleJob[]};
const names={common:'공통',project:'프로젝트',technical:'기술',ps:'PS'};
const blank=():Partial<StyleSource>=>({id:'',title:'',body:'',url:'',kind:'common',origin:'manual'});
export function StylePanel({data,connection,online,drafts,request,refresh}:{data:StyleState;connection:AiConnection;online:boolean;drafts:Draft[];request:(a:string,v?:object)=>Promise<any>;refresh:()=>Promise<void>}){
 const [source,setSource]=useState(blank);const [ids,setIds]=useState<string[]>([]);const [name,setName]=useState('나의 블로그 문체');const [kind,setKind]=useState<StyleKind>('common');const [model,setModel]=useState('');const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [profile,setProfile]=useState<{id?:string;version:number;jobId?:string;name:string;kind:StyleKind;rules:string}>();const [history,setHistory]=useState<StyleProfile[]>([]);
 useEffect(()=>{if(!connection.models.some(m=>m.id===model))setModel((connection.models.find(m=>m.isDefault)||connection.models[0])?.id||'');},[connection.models,model]);
 async function run(a:string,v:object={}){setBusy(true);setMessage('');try{const result=await request(a,v);await refresh();return result;}catch(e){setMessage(e instanceof Error?e.message:'요청 실패');}finally{setBusy(false);}}
 return <div className="style-workspace"><section className="panel"><h2>1. 대표 글 모으기</h2><p>공개 글을 가져오거나 본문을 붙여넣으세요. 분석할 때 선택한 글만 ChatGPT로 보냅니다.</p><fieldset disabled={busy}><label>기존 글 URL<input value={source.url} onChange={e=>setSource({...source,url:e.target.value})}/></label><button onClick={async()=>{const v=await run('style-import',{url:source.url});if(v)setSource({...blank(),...v,origin:'url'});}}>공개 글 본문 가져오기</button><p className="help">현재 연결한 블로그의 개별 공개 글만 지원합니다. 자동 수집이 실패하면 아래 본문에 붙여넣으세요. 광고·메뉴 제거 결과를 저장 전에 확인해주세요.</p><label>대표 글 제목<input maxLength={200} value={source.title} onChange={e=>setSource({...source,title:e.target.value})}/></label><label>대표 글 유형<select aria-label="대표 글 유형" value={source.kind} onChange={e=>setSource({...source,kind:e.target.value as StyleKind})}>{Object.entries(names).map(([v,n])=><option key={v} value={v}>{n}</option>)}</select></label><label>대표 글 본문<textarea rows={9} maxLength={50000} value={source.body} onChange={e=>setSource({...source,body:e.target.value})}/></label><button className="primary" onClick={async()=>{const v=await run('style-source-save',{source});if(v){setSource(blank());setMessage('대표 글을 저장했습니다. 분석할 글을 선택하세요.');}}}>대표 글 저장</button><button onClick={()=>setSource(blank())}>입력 비우기</button><details><summary>직접 수정한 원고를 대표 글로 가져오기</summary><p className="help">자동으로 학습하지 않습니다. 검토·수정한 원고만 직접 선택하세요.</p><select aria-label="수정 원고 가져오기" value="" onChange={e=>{const d=drafts.find(d=>d.id===e.target.value);if(d)setSource({...blank(),title:d.title,body:d.markdown,kind:d.kind,origin:'draft'});}}><option value="">원고 선택</option>{drafts.map(d=><option key={d.id} value={d.id}>{d.title} · v{d.version}</option>)}</select></details></fieldset></section>
 <section className="panel"><h2>2. 선택한 글의 문체 분석</h2><fieldset disabled={busy}>{data.sources.map(s=><div className="source-row" key={s.id}><label><input type="checkbox" checked={ids.includes(s.id)} onChange={e=>setIds(e.target.checked?[...ids,s.id]:ids.filter(id=>id!==s.id))}/>{s.title} <small>{names[s.kind]} · {s.body.length}자</small></label><button onClick={()=>setSource(s)}>본문 확인·수정</button><button onClick={async()=>{if(window.confirm('대표 글 목록에서 제외할까요? 이미 확정한 문체와 작업의 참조 사본은 유지됩니다.')){await run('style-source-remove',{id:s.id});setIds(ids.filter(id=>id!==s.id));}}}>제외</button></div>)}{!data.sources.length&&<p>저장된 대표 글이 없습니다.</p>}<label>문체 이름<input maxLength={100} value={name} onChange={e=>setName(e.target.value)}/></label><label>분석할 문체 유형<select value={kind} onChange={e=>setKind(e.target.value as StyleKind)}>{Object.entries(names).map(([v,n])=><option key={v} value={v}>{n}</option>)}</select></label><button disabled={!online} onClick={()=>void run('ai-connect')}>ChatGPT 연결 확인</button><span>{connection.message}</span>{connection.authUrl&&<a href={connection.authUrl} target="_blank" rel="noreferrer">ChatGPT 로그인 ↗</a>}<label>분석 모델<select value={model} onChange={e=>setModel(e.target.value)}>{connection.models.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label><button className="primary" disabled={!online||connection.state!=='connected'||ids.length<1||ids.length>20||data.jobs.some(j=>['queued','running'].includes(j.state))} onClick={()=>void run('style-analyze',{ids,name,kind,model})}>선택한 {ids.length}개 글 분석</button><p className="help">1~20개 선택 가능. 글이 적거나 유형이 섞이면 분석 한계를 확인하세요. 긴 글은 앞·뒤를 발췌하며 총 약 4만 자 이내로 분석합니다.</p></fieldset>
 {data.jobs.map(j=><div className="ai-result" key={j.id}><h3>{j.name} · {names[j.kind]}</h3><p>{j.step}</p>{j.output&&<><ul>{j.output.observations.map((s,i)=><li key={i}>{s}</li>)}</ul><ul>{j.output.warnings.map((s,i)=><li key={i}>{s}</li>)}</ul><button onClick={()=>{setProfile({version:0,jobId:j.id,name:j.name,kind:j.kind,rules:j.output!.rules});setHistory([]);}}>분석 규칙 검토</button></>}{['queued','running'].includes(j.state)&&<button disabled={busy||j.cancel} onClick={()=>void run('style-cancel',{id:j.id})}>분석 취소</button>}{j.state==='failed'&&j.attempts<2&&<button disabled={busy||!online} onClick={()=>void run('style-retry',{id:j.id})}>분석 한 번 재시도</button>}{j.usage&&<small>반환 사용량 {j.usage.total} 토큰</small>}</div>)}</section>
 <section className="panel"><h2>3. 규칙 수정·확정</h2><p>확정한 문체는 원고의 AI 생성 화면에서 선택할 수 있습니다. 기본 문체와 각각 생성하면 결과를 비교할 수 있어요.</p>{data.profiles.map(p=><button key={p.id} onClick={async()=>{setProfile(p);setHistory(await request('style-history',{id:p.id}).catch(()=>[]));}}>{p.name} · {names[p.kind]} · v{p.version}</button>)}{profile&&<fieldset disabled={busy}><label>확정할 문체 이름<input value={profile.name} maxLength={100} onChange={e=>setProfile({...profile,name:e.target.value})}/></label><label>문체 규칙<textarea aria-label="문체 규칙" rows={12} maxLength={10000} value={profile.rules} onChange={e=>setProfile({...profile,rules:e.target.value})}/></label><button className="primary" onClick={async()=>{const p=await run('style-profile-save',{profile});if(p){setProfile(p);setMessage(`문체 v${p.version}을 확정했습니다.`);}}}>문체 확정 저장</button></fieldset>}{history.length>0&&<details><summary>문체 버전 이력</summary>{history.map(p=><details key={p.version}><summary>v{p.version} · {p.name}</summary><pre>{p.rules}</pre></details>)}</details>}</section>{message&&<div className="notice" role="status">{message}</div>}</div>;
}
